function Hd = iirButter(sampling,first, second)
%IIRBUTTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
% Generated on: 19-Dec-2018 18:04:37

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = sampling;  % Sampling Frequency

N   = 60;    % Order
Fc1 = first;  % First Cutoff Frequency
Fc2 = second;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
